name: Java CI/CD with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: neondb_owner
          POSTGRES_PASSWORD: npg_Hohp8aYBU2sj
          POSTGRES_DB: neondb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: |
        cd minicloud
        ./mvnw clean package -DskipTests=true

    - name: Build Docker Image
      run: |
        docker build -t miniaws-api:latest ./minicloud/minicloud-api

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: minicloud-api-jar
        path: minicloud/minicloud-api/target/*.jar
